### ISSUE TITLE
SCS.Optimizer Verbose Issue

### ISSUE THREAD

**Issue by vijeycreative** [ericproffitt/MaxCut.jl#1]
Hey there,

In line 39 replace the following code 
`solve!(problem, SCS.Optimizer(verbose=false))`
with
`solve!(problem, SCS.Optimizer(); silent_solver=true)`.

Thanks :)

**Comment by ericproffitt** [comment]
does `solve!(problem, SCS.Optimizer(verbose=false))` not work for you?

All three of these seem to work,

```julia
solve!(problem, SCS.Optimizer(verbose=false))
solve!(problem, SCS.Optimizer(); silent_solver=true)
solve!(problem, SCS.Optimizer; silent_solver=true)
```

I'm not sure which is the preferred syntax.

**Comment by vijeycreative** [comment]
For the first code `solve!(problem, SCS.Optimizer(verbose=false))` I'm getting the error

> MethodError: no method matching SCS.Optimizer(; verbose=false)
> Closest candidates are:
>   SCS.Optimizer() at ~/.julia/packages/SCS/JD7s9/src/MOI_wrapper/MOI_wrapper.jl:133 got unsupported keyword argument "verbose"
> 
> Stacktrace:
>  [1] maxcut(W::Matrix{Float64}; iter::Int64, tol::Int64)
>    @ Main.GeomansWilliamson ~/Documents/XQAOA_Julia/XQAOA/Geomans_Williamson.jl:42
>  [2] maxcut(W::Matrix{Float64})
>    @ Main.GeomansWilliamson ~/Documents/XQAOA_Julia/XQAOA/Geomans_Williamson.jl:12
>  [3] top-level scope
>    @ ./timing.jl:220 [inlined]
>  [4] top-level scope
>    @ ./In[4]:0
>  [5] eval
>    @ ./boot.jl:373 [inlined]
>  [6] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
>    @ Base ./loading.jl:1196

The other two codes are working properly. I'm using Julia 1.7 and my packages are of the following version:
1. Convex v0.15.2
2. SCS v1.1.2

I guess the first code got deprecated in later releases. Hope this helps :)

**Comment by ericproffitt** [comment]
Thanks it does, looks like my versions are outdated.

Fixed in main.
